version: "3"
services:
  analytics-consumer:
    build:
      context: ./input-adapter-spark
    networks:
      - wikiflow-network
    ports:
      - "4040:4040"
    volumes:
      - delta:/storage
networks:
  wikiflow-network:
    external:
      name: wikiflow-network
volumes:
  delta: