version: '2'
services:
  verticadb:
    image: dataplatform/docker-vertica
    container_name: otus_hw_8_vertica
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - ./vertica_data:/home/dbadmin/docker
